version: '3.8'
services:

  mysql:
    image: 'mysql:latest'
    container_name: coffee-mysql
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: coffee
      MYSQL_USER: coffee
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  sonarqube:
    image: sonarqube:10.3.0-community
    container_name: sonar
    restart: on-failure
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: 'jdbc:postgresql://postgres:5432/sonar'
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - './sonarqube/sonarqube_data:/opt/sonarqube/data'
      - './sonarqube/sonarqube_extensions:/opt/sonarqube/extensions'
      - './sonarqube/sonarqube_logs:/opt/sonarqube/logs'
    ports:
      - '9000:9000'

  postgres:
    image: postgres
    container_name: postgres
    restart: on-failure
    volumes:
      - './postgres/postgres_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_LANG=en_US.UTF-8 
    restart: always

