server:
  port: 8090
  shutdown: graceful

spring:
  mvc:
    problem details:
      enabled: true
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/coffee
    username: coffee
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true